base_url = "https://caden.codes"
title = "Caden Kriese"
description = "Caden Kriese's personal website."
default_language = "en"
generate_feeds = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
github_url = "https://github.com/cadenkriese"
linkedin_url = "https://www.linkedin.com/in/caden-kriese/"
